FROM ubuntu:18.04


RUN apt-get update && apt-get install -y software-properties-common \
    && add-apt-repository ppa:ondrej/php                            \
    && apt-get update                                               \
    && apt-get install -y                                           \
    nginx                                                           \
    sqlite3                                                         \
    php7.4-fpm                                                      \
    php7.4-mysql                                                    \
    php7.4-intl                                                     \
    php7.4-mbstring                                                 \
    php7.4-zip                                                      \
    php7.4-xml                                                      \
    php7.4-sqlite3


#
# When added to the first run command it opens up a tzconfig question
# and will not finish installation. have this on separate RUN instead
#
RUN apt-get install -y git

COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY docker/php.ini /etc/php/7.4/fpm/php.ini
COPY docker/default /etc/nginx/sites-available/default

WORKDIR /var/www/html

CMD service php7.4-fpm start    \
    && nginx -g 'daemon off;'   \
    && bash    
